name: flutter_spinkit
description: A collection of loading indicators animated with flutter. Heavily inspired by @tobiasahlin's SpinKit.
version: 4.1.2+1
homepage: https://github.com/jogboms/flutter_spinkit

authors:
  - Jeremiah Ogbomo <jeremiahogbomo@gmail.com>
  - Ayush Agarwal <aagarwal9782@gmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
